### ISSUE TITLE
encryptConfigs.js Error

### ISSUE THREAD

**Issue by cabbagehead** [trendmicro/SecureCodingDojo#15]
We are receiving the following error when running encryptConfigs.js

[root@localhost tools]# sudo -u scd node encryptConfigs.js
/opt/scd/SecureCodingDojo/trainingportal/config.js:5
config.isSecure = config.dojoUrl.startsWith("https");
                                 ^

TypeError: Cannot read property 'startsWith' of undefined
    at Object.<anonymous> (/opt/scd/SecureCodingDojo/trainingportal/config.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/scd/SecureCodingDojo/trainingportal/aescrypto.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
[root@localhost tools]#

Any help would be appreciated.  Thanks

**Comment by paul-ion** [comment]
Looks like you're missing the DOJO_URL environment variable. While you're there also configure the other environment variables too: https://github.com/trendmicro/SecureCodingDojo/wiki/Running-the-training-portal#configuring-encryption-key-seeds-and-other-environment-variables

**Comment by cabbagehead** [comment]
Thanks, it looks like my input didn't take originally.
